global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'grekko-services'
    static_configs:
      - targets: 
        - 'host.docker.internal:8000'  # Main API
        - 'host.docker.internal:8001'  # Agent Coordination
        - 'host.docker.internal:8002'  # Risk Management
        - 'host.docker.internal:8003'  # Coinbase Integration
        - 'host.docker.internal:8004'  # MetaMask Integration
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'docker'
    static_configs:
      - targets: ['host.docker.internal:9323']
