# Configuration for Grekko Trading Bot

# General settings
general:
  log_level: INFO  # Options: DEBUG, INFO, WARNING, ERROR, CRITICAL
  timezone: UTC
  version: 0.1.0
  default_exchange: binance  # Default exchange for trading
  default_strategy: momentum  # Options: arbitrage, mean_reversion, momentum, sentiment

# Autonomous agent settings
agent:
  auto_start: false  # Set to true to auto-start the trading agent
  config_file: config/agent_config.yaml
  status_report_interval: 3600  # Status report interval in seconds

# Database settings
database:
  type: sqlite
  connection_string: sqlite:///grekko.db

# API server for mobile app
api_server:
  enable: true
  host: 0.0.0.0
  port: 8000
  jwt_secret_key_env: JWT_SECRET_KEY
  access_token_expire_minutes: 30

# ECDSA-secured config vault
config_vault:
  encryption: AES-256-GCM
  key_management: ECDSA
  vault_file: .grekko/config_vault.enc

# Credentials management
credentials:
  vault_path: ~/.grekko/credentials.grekko
  encryption: "AES-256-GCM"  # Encryption algorithm for the vault
  rotation_period_days: 30  # Reminder to rotate API keys periodically
  require_2fa: false  # Future enhancement for 2FA on vault access
  min_password_length: 8  # Minimum password length for vault

# CCXT Pro integration
ccxt_pro:
  enable: true
  rate_limit_handling: automatic
  timeout_ms: 30000

# Web3.py and Solders.py integration
web3:
  enable: true
  provider: https://mainnet.infura.io/v3/YOUR_INFURA_PROJECT_ID
  gas_limit_multiplier: 1.1
  gas_price_strategy: medium

solders:
  enable: true
  provider: https://api.mainnet-beta.solana.com
  commitment: confirmed

# Candlestick stream multiplexer
candlestick_stream:
  websocket: true
  rest_fallback: true
  timeframes:
    - 1m
    - 5m
    - 15m
    - 1h
    - 4h
    - 1d

# Risk management settings
risk:
  initial_capital: 10000.0
  max_position_size_pct: 0.15  # Maximum position size as percentage of capital
  max_risk_per_trade_pct: 0.01  # Risk per trade (1% of capital)
  max_drawdown_pct: 0.10  # Maximum drawdown before triggering circuit breaker
  max_open_positions: 5  # Maximum number of open positions
  max_concentration_pct: 0.30  # Maximum exposure to a single asset
  
  # Circuit breaker settings
  circuit_breaker:
    enable: true
    cooldown_minutes: 30
    max_consecutive_losses: 3
    volatility_threshold: 2.5  # Volatility multiplier threshold
    
  # Stop loss settings
  stop_loss:
    enable: true
    default_stop_pct: 0.05  # Default stop loss (5% from entry)
    trailing_stop_enable: true
    trailing_stop_activation_pct: 0.02  # Trailing stop activates after 2% profit
    trailing_stop_distance_pct: 0.03  # Trailing stop follows at 3% distance

# Performance tracking
performance:
  metrics:
    - win_rate
    - profit_factor
    - sharpe_ratio
    - max_drawdown
  track_trades: true
  backtesting_mode: false

# Notifications
notifications:
  email:
    enable: false
    smtp_server: smtp.example.com
    smtp_port: 587
    from_email: grekko@example.com
  
  mobile:
    enable: true
    trade_notifications: true
    error_notifications: true