# Kubernetes Cluster Configuration for Autonomous Trading System
# Production cluster: 6 workers + 3 masters with high availability
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-config
  namespace: kube-system
data:
  cluster-name: "grekko-trading-prod"
  cluster-version: "1.28"
  node-count: "9"
  worker-nodes: "6"
  master-nodes: "3"
---
# Cluster Autoscaler Configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-autoscaler-status
  namespace: kube-system
data:
  nodes.max: "12"
  nodes.min: "6"
  scale-down-enabled: "true"
  scale-down-delay-after-add: "10m"
  scale-down-unneeded-time: "10m"
---
# Node Affinity Rules for Trading Services
apiVersion: v1
kind: ConfigMap
metadata:
  name: node-affinity-config
  namespace: trading-prod
data:
  application-nodes: |
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node-type
            operator: In
            values: ["application"]
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        preference:
          matchExpressions:
          - key: performance-tier
            operator: In
            values: ["high"]
  
  data-nodes: |
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node-type
            operator: In
            values: ["data"]
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        preference:
          matchExpressions:
          - key: storage-tier
            operator: In
            values: ["ssd"]
---
# Resource Limits and Quotas
apiVersion: v1
kind: ResourceQuota
metadata:
  name: trading-prod-quota
  namespace: trading-prod
spec:
  hard:
    requests.cpu: "20"
    requests.memory: 40Gi
    limits.cpu: "40"
    limits.memory: 80Gi
    persistentvolumeclaims: "10"
    services: "20"
    secrets: "50"
    configmaps: "50"
---
# Network Policy for Cluster Security
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
  namespace: trading-prod
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
---
# Allow inter-service communication within trading namespace
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-trading-services
  namespace: trading-prod
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/part-of: trading-system
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: trading-prod
    - namespaceSelector:
        matchLabels:
          name: istio-system
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: trading-prod
    - namespaceSelector:
        matchLabels:
          name: istio-system
  - to: []
    ports:
    - protocol: TCP
      port: 443  # HTTPS
    - protocol: TCP
      port: 53   # DNS
    - protocol: UDP
      port: 53   # DNS
---
# Pod Disruption Budget for High Availability
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: trading-services-pdb
  namespace: trading-prod
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/part-of: trading-system
      tier: critical
---
# Horizontal Pod Autoscaler for Trading Services
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: trading-services-hpa
  namespace: trading-prod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: execution-engine
  minReplicas: 3
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60